version: '2'
services:
    goweb:
        restart: always
        ports:
            - "8080:8080"
        build:
            context: ./goweb
            dockerfile: ./Dockerfile
        command: go run /myapp/main.go
    nginx:
        restart: always
        build:
            context: ./nginx/
            dockerfile: ./Dockerfile
        links:
            - goweb
        volumes:
            - /www/static
        ports:
            - "80:80"
    postgres:
        restart: always
        image: postgres:latest
        volumes:
            - /var/lib/postgresql
        ports:
            - "5432:5432"

