version: '2'
services:
    goweb:
        restart: always
        ports:
            - "8080:8080"
        build:
            context: ./goweb
            dockerfile: ./Dockerfile
        links:
            - postgres
        expose:
            - "8080"
        depends_on:
            - postgres
    nginx:
        restart: always
        build:
            context: ./nginx/
            dockerfile: ./Dockerfile
        links:
            - goweb
        volumes:
            - /www/static
        ports:
            - "80:80"
    postgres:
        restart: always
        build:
            context: ./postgres
            dockerfile: ./Dockerfile
        volumes:
            - /var/lib/postgresql
        ports:
            - "5432:5432"
        environment:
            dbUsername: postgres
            dbPassword: postgres
            dbName: postgres
